2024-12-20 09:51:20,427 - INFO - Starting TCP Server Service...
2024-12-20 09:51:20,427 - INFO - Running command: python "C:\Users\ADMIN\Desktop\Standard Introductory Test Task\server.py"
2024-12-20 10:00:00,354 - INFO - Starting TCP Server Service...
2024-12-20 10:00:00,354 - INFO - Running command: python "C:\Users\ADMIN\Desktop\Standard Introductory Test Task\server.py"
2024-12-20 10:01:58,982 - INFO - Starting TCP Server Service...
2024-12-20 10:01:58,982 - INFO - Running command: python "C:\Users\ADMIN\Desktop\Standard Introductory Test Task\server.py"
2024-12-20 10:02:07,097 - INFO - Starting TCP Server Service...
2024-12-20 10:02:07,098 - INFO - Running command: python "C:\Users\ADMIN\Desktop\Standard Introductory Test Task\server.py"
2024-12-20 15:03:47,461 - INFO - Starting TCP Server Service...
2024-12-20 15:03:47,461 - INFO - Running command: python "C:\Users\ADMIN\Desktop\Standard Introductory Test Task\server.py"
2025-03-12 16:23:38.094 | INFO     | __main__:<module>:31 - Starting TCP Server Service...
2025-03-12 16:23:38.094 | ERROR    | __main__:<module>:485 - Unhandled exception: CONFIG_PATH environment variable must be set.
2025-03-12 16:25:39.390 | INFO     | __main__:<module>:31 - Starting TCP Server Service...
2025-03-12 16:25:39.427 | INFO     | __main__:start:258 - Creating SSL context...
2025-03-12 16:25:39.427 | INFO     | __main__:start:268 - Server started on ('0.0.0.0', 44445)
2025-03-12 16:25:39.428 | INFO     | __main__:start:270 - Server is running...
2025-03-12 16:26:18.273 | INFO     | __main__:handle_client:159 - Client connected: ('127.0.0.1', 52987)
2025-03-12 16:26:18.274 | INFO     | __main__:handle_client:200 - Request from client ('127.0.0.1', 52987): hello
2025-03-12 16:26:18.274 | DEBUG    | __main__:handle_client:205 - DEBUG: Rereading file content for ('127.0.0.1', 52987) as reread_on_query is True.
2025-03-12 16:26:18.599 | INFO     | __mp_main__:<module>:31 - Starting TCP Server Service...
2025-03-12 16:26:18.602 | INFO     | __main__:handle_client:221 - Response Time: 0.3276 seconds
2025-03-12 16:26:18.602 | INFO     | __main__:handle_client:223 - Response sent to client: ('127.0.0.1', 52987)
2025-03-12 16:26:18.602 | INFO     | __main__:handle_client:224 - Connection closed for client: ('127.0.0.1', 52987)
2025-03-12 16:26:18.602 | DEBUG    | __main__:handle_client:227 - DEBUG: Client IP: 127.0.0.1, Total Execution Time: 0.3290 seconds
2025-03-12 16:27:09.088 | INFO     | __main__:<module>:482 - Server interrupted by keyboard, exiting...
2025-03-12 16:28:41,536 - INFO - Starting TCP Server Service...
2025-03-12 16:28:41,543 - INFO - Creating SSL context...
2025-03-12 16:28:41,544 - INFO - Server sktarted on ('0.0.0.0', 44445)
2025-03-12 16:28:41,544 - INFO - Server is running...
2025-03-12 16:28:57,731 - INFO - Client connected: ('127.0.0.1', 53012)
2025-03-12 16:28:57,732 - INFO - Request from client ('127.0.0.1', 53012): hello world
2025-03-12 16:28:57,975 - INFO - Starting TCP Server Service...
2025-03-12 16:28:57,978 - INFO - Response Time: 0.2452 seconds
2025-03-12 16:28:57,978 - INFO - Response sent to client: ('127.0.0.1', 53012)
2025-03-12 16:28:57,978 - INFO - Connection closed for client: ('127.0.0.1', 53012)
2025-03-12 16:28:58,990 - INFO - Memory Usage: 87.1%
2025-03-12 16:28:58,990 - INFO - CPU Usage: 12.4%
2025-03-12 16:28:58,991 - INFO - Total Requests: 1, Successful Requests: 1, Failed Requests: 0
2025-03-12 16:29:48,061 - INFO - Client connected: ('127.0.0.1', 53020)
2025-03-12 16:29:48,063 - INFO - Request from client ('127.0.0.1', 53020): hello
2025-03-12 16:29:48,068 - INFO - Response Time: 0.0051 seconds
2025-03-12 16:29:48,069 - INFO - Response sent to client: ('127.0.0.1', 53020)
2025-03-12 16:29:48,069 - INFO - Connection closed for client: ('127.0.0.1', 53020)
2025-03-12 16:29:49,084 - INFO - Memory Usage: 87.2%
2025-03-12 16:29:49,084 - INFO - CPU Usage: 12.1%
2025-03-12 16:29:49,084 - INFO - Total Requests: 2, Successful Requests: 2, Failed Requests: 0
2025-03-12 16:50:22,839 - INFO - Server interrupted by keyboard, exiting...
2025-03-12 16:53:41,814 - INFO - Starting TCP Server Service...
2025-03-12 16:53:41,822 - INFO - Creating SSL context...
2025-03-12 16:53:41,822 - INFO - Server started on ('0.0.0.0', 44445)
2025-03-12 16:53:41,822 - INFO - Server is running...
2025-03-12 16:53:54,693 - INFO - Client connected: ('127.0.0.1', 53438)
2025-03-12 16:53:54,695 - INFO - Request from client ('127.0.0.1', 53438): hello
2025-03-12 16:53:54,942 - INFO - Starting TCP Server Service...
2025-03-12 16:53:54,945 - INFO - Response Time: 0.2483 seconds
2025-03-12 16:53:54,945 - INFO - Response sent to client: ('127.0.0.1', 53438)
2025-03-12 16:53:54,945 - INFO - Connection closed for client: ('127.0.0.1', 53438)
2025-03-12 16:53:55,954 - INFO - Memory Usage: 81.7%
2025-03-12 16:53:55,954 - INFO - CPU Usage: 14.4%
2025-03-12 16:53:55,954 - INFO - Total Requests: 1, Successful Requests: 1, Failed Requests: 0
2025-03-12 16:54:21,261 - INFO - Client connected: ('127.0.0.1', 53445)
2025-03-12 16:54:21,262 - INFO - Request from client ('127.0.0.1', 53445): hello world
2025-03-12 16:54:21,266 - INFO - Response Time: 0.0037 seconds
2025-03-12 16:54:21,266 - INFO - Response sent to client: ('127.0.0.1', 53445)
2025-03-12 16:54:21,267 - INFO - Connection closed for client: ('127.0.0.1', 53445)
2025-03-12 16:54:22,280 - INFO - Memory Usage: 81.6%
2025-03-12 16:54:22,281 - INFO - CPU Usage: 12.9%
2025-03-12 16:54:22,281 - INFO - Total Requests: 2, Successful Requests: 2, Failed Requests: 0
2025-03-17 01:30:09,444 - INFO - Starting TCP Server Service...
2025-03-17 01:30:09,446 - ERROR - Unhandled exception: CONFIG_PATH environment variable must be set.
Traceback (most recent call last):
  File "/mnt/c/Users/ADMIN/Desktop/Standard Introductory Test Task/server.py", line 486, in <module>
    main()
  File "/mnt/c/Users/ADMIN/Desktop/Standard Introductory Test Task/server.py", line 444, in main
    raise ValueError("CONFIG_PATH environment variable must be set.")
ValueError: CONFIG_PATH environment variable must be set.
2025-03-17 01:30:42,519 - INFO - Starting TCP Server Service...
2025-03-17 01:30:42,519 - ERROR - Unhandled exception: CONFIG_PATH environment variable must be set.
Traceback (most recent call last):
  File "/mnt/c/Users/ADMIN/Desktop/Standard Introductory Test Task/server.py", line 486, in <module>
    main()
  File "/mnt/c/Users/ADMIN/Desktop/Standard Introductory Test Task/server.py", line 444, in main
    raise ValueError("CONFIG_PATH environment variable must be set.")
ValueError: CONFIG_PATH environment variable must be set.
2025-03-17 01:39:04,924 - INFO - Starting TCP Server Service...
2025-03-17 01:39:04,924 - ERROR - Unhandled exception: CONFIG_PATH environment variable must be set.
Traceback (most recent call last):
  File "/mnt/c/Users/ADMIN/Desktop/Standard Introductory Test Task/server.py", line 486, in <module>
    main()
  File "/mnt/c/Users/ADMIN/Desktop/Standard Introductory Test Task/server.py", line 444, in main
    raise ValueError("CONFIG_PATH environment variable must be set.")
ValueError: CONFIG_PATH environment variable must be set.
2025-03-17 01:39:46,915 - INFO - Starting TCP Server Service...
2025-03-17 01:39:46,916 - ERROR - Unhandled exception: CONFIG_PATH environment variable must be set.
Traceback (most recent call last):
  File "/mnt/c/Users/ADMIN/Desktop/Standard Introductory Test Task/server.py", line 486, in <module>
    main()
  File "/mnt/c/Users/ADMIN/Desktop/Standard Introductory Test Task/server.py", line 444, in main
    raise ValueError("CONFIG_PATH environment variable must be set.")
ValueError: CONFIG_PATH environment variable must be set.
2025-03-17 01:53:49,555 - INFO - Starting TCP Server Service...
2025-03-17 01:53:49,557 - ERROR - Unhandled exception: CONFIG_PATH environment variable must be set.
Traceback (most recent call last):
  File "/mnt/c/Users/ADMIN/Desktop/Standard Introductory Test Task/server.py", line 486, in <module>
    main()
  File "/mnt/c/Users/ADMIN/Desktop/Standard Introductory Test Task/server.py", line 444, in main
    raise ValueError("CONFIG_PATH environment variable must be set.")
ValueError: CONFIG_PATH environment variable must be set.
2025-03-17 02:02:52,185 - INFO - Starting TCP Server Service...
2025-03-17 02:02:52,186 - ERROR - Unhandled exception: CONFIG_PATH environment variable must be set.
Traceback (most recent call last):
  File "/home/ruby/project/server.py", line 486, in <module>
    main()
  File "/home/ruby/project/server.py", line 444, in main
    raise ValueError("CONFIG_PATH environment variable must be set.")
ValueError: CONFIG_PATH environment variable must be set.
2025-03-17 02:04:46,457 - INFO - Starting TCP Server Service...
2025-03-17 02:04:46,458 - ERROR - Unhandled exception: CONFIG_PATH environment variable must be set.
Traceback (most recent call last):
  File "/home/ruby/project/server.py", line 486, in <module>
    main()
  File "/home/ruby/project/server.py", line 444, in main
    raise ValueError("CONFIG_PATH environment variable must be set.")
ValueError: CONFIG_PATH environment variable must be set.
2025-03-17 02:06:03,588 - INFO - Starting TCP Server Service...
2025-03-17 02:06:03,589 - ERROR - Unhandled exception: CONFIG_PATH environment variable must be set.
Traceback (most recent call last):
  File "/home/ruby/project/server.py", line 486, in <module>
    main()
  File "/home/ruby/project/server.py", line 444, in main
    raise ValueError("CONFIG_PATH environment variable must be set.")
ValueError: CONFIG_PATH environment variable must be set.
2025-03-17 02:11:39,301 - INFO - Client connected: ('127.0.0.1', 50180)
2025-03-17 02:11:39,316 - INFO - Request from client ('127.0.0.1', 50180): hello
2025-03-17 02:11:39,518 - INFO - Response Time: 0.2003 seconds
2025-03-17 02:11:39,521 - INFO - Response sent to client: ('127.0.0.1', 50180)
2025-03-17 02:11:39,521 - INFO - Connection closed for client: ('127.0.0.1', 50180)
2025-03-17 02:11:40,565 - INFO - Memory Usage: 82.6%
2025-03-17 02:11:40,565 - INFO - CPU Usage: 55.9%
2025-03-17 02:11:40,565 - INFO - Total Requests: 3, Successful Requests: 3, Failed Requests: 0
2025-03-17 02:11:50,601 - INFO - Client connected: ('127.0.0.1', 50185)
2025-03-17 02:11:50,604 - INFO - Request from client ('127.0.0.1', 50185): hello world
2025-03-17 02:11:50,615 - INFO - Response Time: 0.0096 seconds
2025-03-17 02:11:50,616 - INFO - Response sent to client: ('127.0.0.1', 50185)
2025-03-17 02:11:50,617 - INFO - Connection closed for client: ('127.0.0.1', 50185)
2025-03-17 02:11:51,648 - INFO - Memory Usage: 82.7%
2025-03-17 02:11:51,649 - INFO - CPU Usage: 64.5%
2025-03-17 02:11:51,650 - INFO - Total Requests: 4, Successful Requests: 4, Failed Requests: 0
2025-03-17 02:11:53,620 - INFO - Server interrupted by keyboard, exiting...
2025-03-17 02:11:56,808 - INFO - Starting TCP Server Service...
2025-03-17 02:11:56,851 - INFO - Creating SSL context...
2025-03-17 02:11:56,852 - INFO - Server started on ('0.0.0.0', 44445)
2025-03-17 02:11:56,852 - INFO - Server is running...
2025-03-17 02:12:04,170 - INFO - Client connected: ('127.0.0.1', 50193)
2025-03-17 02:12:04,171 - INFO - Request from client ('127.0.0.1', 50193): hello world
2025-03-17 02:12:04,576 - INFO - Starting TCP Server Service...
2025-03-17 02:12:04,583 - INFO - Response Time: 0.4088 seconds
2025-03-17 02:12:04,583 - INFO - Response sent to client: ('127.0.0.1', 50193)
2025-03-17 02:12:04,583 - INFO - Connection closed for client: ('127.0.0.1', 50193)
2025-03-17 02:12:05,601 - INFO - Memory Usage: 83.0%
2025-03-17 02:12:05,601 - INFO - CPU Usage: 58.6%
2025-03-17 02:12:05,601 - INFO - Total Requests: 1, Successful Requests: 1, Failed Requests: 0
2025-03-17 02:16:54,541 - INFO - Starting TCP Server Service...
2025-03-17 02:16:54,541 - ERROR - Unhandled exception: CONFIG_PATH environment variable must be set.
Traceback (most recent call last):
  File "/home/ruby/project/server.py", line 486, in <module>
    main()
  File "/home/ruby/project/server.py", line 444, in main
    raise ValueError("CONFIG_PATH environment variable must be set.")
ValueError: CONFIG_PATH environment variable must be set.
2025-03-17 02:23:03,749 - INFO - Starting TCP Server Service...
2025-03-17 02:23:03,750 - ERROR - Unhandled exception: CONFIG_PATH environment variable must be set.
Traceback (most recent call last):
  File "/home/ruby/project/server.py", line 486, in <module>
    main()
  File "/home/ruby/project/server.py", line 444, in main
    raise ValueError("CONFIG_PATH environment variable must be set.")
ValueError: CONFIG_PATH environment variable must be set.
2025-03-17 02:23:56,157 - INFO - Server interrupted by keyboard, exiting...
2025-03-17 02:23:59,706 - INFO - Starting TCP Server Service...
2025-03-17 02:23:59,720 - INFO - Creating SSL context...
2025-03-17 02:23:59,721 - INFO - Server started on ('0.0.0.0', 44445)
2025-03-17 02:23:59,722 - INFO - Server is running...
2025-03-17 02:24:13,918 - INFO - Client connected: ('127.0.0.1', 50443)
2025-03-17 02:24:13,918 - INFO - Request from client ('127.0.0.1', 50443): test
2025-03-17 02:24:14,315 - INFO - Starting TCP Server Service...
2025-03-17 02:24:14,319 - INFO - Response Time: 0.4002 seconds
2025-03-17 02:24:14,319 - INFO - Response sent to client: ('127.0.0.1', 50443)
2025-03-17 02:24:14,319 - INFO - Connection closed for client: ('127.0.0.1', 50443)
2025-03-17 02:24:15,334 - INFO - Memory Usage: 87.7%
2025-03-17 02:24:15,335 - INFO - CPU Usage: 61.7%
2025-03-17 02:24:15,335 - INFO - Total Requests: 1, Successful Requests: 1, Failed Requests: 0
2025-03-17 02:24:21,660 - INFO - Client connected: ('127.0.0.1', 50447)
2025-03-17 02:24:21,662 - INFO - Request from client ('127.0.0.1', 50447): test file
2025-03-17 02:24:21,668 - INFO - Response Time: 0.0077 seconds
2025-03-17 02:24:21,672 - INFO - Response sent to client: ('127.0.0.1', 50447)
2025-03-17 02:24:21,674 - INFO - Connection closed for client: ('127.0.0.1', 50447)
2025-03-17 02:24:22,695 - INFO - Memory Usage: 87.6%
2025-03-17 02:24:22,695 - INFO - CPU Usage: 62.1%
2025-03-17 02:24:22,695 - INFO - Total Requests: 2, Successful Requests: 2, Failed Requests: 0
2025-03-17 02:24:53,665 - INFO - Client connected: ('127.0.0.1', 50456)
2025-03-17 02:24:53,668 - INFO - Request from client ('127.0.0.1', 50456): test string
2025-03-17 02:24:53,676 - INFO - Response Time: 0.0076 seconds
2025-03-17 02:24:53,677 - INFO - Response sent to client: ('127.0.0.1', 50456)
2025-03-17 02:24:53,678 - INFO - Connection closed for client: ('127.0.0.1', 50456)
2025-03-17 02:24:54,714 - INFO - Memory Usage: 87.7%
2025-03-17 02:24:54,716 - INFO - CPU Usage: 55.5%
2025-03-17 02:24:54,716 - INFO - Total Requests: 3, Successful Requests: 3, Failed Requests: 0
2025-03-17 02:28:39,205 - INFO - Starting TCP Server Service...
2025-03-17 02:38:33,347 - INFO - Client connected: ('127.0.0.1', 50815)
2025-03-17 02:38:33,349 - INFO - Request from client ('127.0.0.1', 50815): test string
2025-03-17 02:38:33,360 - INFO - Response Time: 0.0096 seconds
2025-03-17 02:38:33,360 - INFO - Response sent to client: ('127.0.0.1', 50815)
2025-03-17 02:38:33,361 - INFO - Connection closed for client: ('127.0.0.1', 50815)
2025-03-17 02:38:34,399 - INFO - Memory Usage: 88.4%
2025-03-17 02:38:34,400 - INFO - CPU Usage: 52.6%
2025-03-17 02:38:34,401 - INFO - Total Requests: 4, Successful Requests: 4, Failed Requests: 0
2025-03-17 02:41:51,647 - INFO - Server interrupted by keyboard, exiting...
2025-03-17 02:42:20,716 - INFO - Starting TCP Server Service...
2025-03-17 02:45:01,226 - INFO - Starting TCP Server Service...
2025-03-17 02:45:01,241 - ERROR - Unhandled exception: [Errno 13] Permission denied: '/var/run/your_server.pid'
Traceback (most recent call last):
  File "/home/ruby/project/server.py", line 486, in <module>
    main()
  File "/home/ruby/project/server.py", line 453, in main
    daemon.start()
  File "/home/ruby/project/server.py", line 380, in start
    self.daemonize()
  File "/home/ruby/project/server.py", line 366, in daemonize
    with open(self.pidfile, 'w+') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/var/run/your_server.pid'
2025-03-17 17:14:47,650 - INFO - Starting TCP Server Service...
2025-03-17 17:14:47,692 - INFO - Creating SSL context...
2025-03-17 17:14:47,693 - INFO - Server started on ('0.0.0.0', 44445)
2025-03-17 17:14:47,693 - INFO - Server is running...
2025-03-17 17:14:56,559 - INFO - Client connected: ('127.0.0.1', 61122)
2025-03-17 17:14:56,560 - INFO - Request from client ('127.0.0.1', 61122): hello
2025-03-17 17:14:56,849 - INFO - Starting TCP Server Service...
2025-03-17 17:14:56,852 - INFO - Response Time: 0.2920 seconds
2025-03-17 17:14:56,852 - INFO - Response sent to client: ('127.0.0.1', 61122)
2025-03-17 17:14:56,853 - INFO - Connection closed for client: ('127.0.0.1', 61122)
2025-03-17 17:14:57,863 - INFO - Memory Usage: 84.4%
2025-03-17 17:14:57,863 - INFO - CPU Usage: 30.0%
2025-03-17 17:14:57,863 - INFO - Total Requests: 1, Successful Requests: 1, Failed Requests: 0
2025-03-17 17:15:06,523 - INFO - Client connected: ('127.0.0.1', 61124)
2025-03-17 17:15:06,524 - INFO - Request from client ('127.0.0.1', 61124): hello world
2025-03-17 17:15:06,530 - INFO - Response Time: 0.0053 seconds
2025-03-17 17:15:06,530 - INFO - Response sent to client: ('127.0.0.1', 61124)
2025-03-17 17:15:06,531 - INFO - Connection closed for client: ('127.0.0.1', 61124)
2025-03-17 17:15:07,549 - INFO - Memory Usage: 84.6%
2025-03-17 17:15:07,549 - INFO - CPU Usage: 17.6%
2025-03-17 17:15:07,549 - INFO - Total Requests: 2, Successful Requests: 2, Failed Requests: 0
2025-03-17 17:18:30,672 - INFO - Starting TCP Server Service...
2025-03-17 17:18:30,674 - ERROR - Unhandled exception: CONFIG_PATH environment variable must be set.
Traceback (most recent call last):
  File "/home/ruby/project/server.py", line 486, in <module>
    main()
  File "/home/ruby/project/server.py", line 444, in main
    raise ValueError("CONFIG_PATH environment variable must be set.")
ValueError: CONFIG_PATH environment variable must be set.
2025-03-17 17:18:34,096 - INFO - Starting TCP Server Service...
2025-03-17 17:18:34,096 - ERROR - Unhandled exception: CONFIG_PATH environment variable must be set.
Traceback (most recent call last):
  File "/home/ruby/project/server.py", line 486, in <module>
    main()
  File "/home/ruby/project/server.py", line 444, in main
    raise ValueError("CONFIG_PATH environment variable must be set.")
ValueError: CONFIG_PATH environment variable must be set.
2025-03-17 17:20:06,472 - INFO - Starting TCP Server Service...
2025-03-17 17:20:06,473 - ERROR - Unhandled exception: CONFIG_PATH environment variable must be set.
Traceback (most recent call last):
  File "/home/ruby/project/server.py", line 486, in <module>
    main()
  File "/home/ruby/project/server.py", line 444, in main
    raise ValueError("CONFIG_PATH environment variable must be set.")
ValueError: CONFIG_PATH environment variable must be set.
2025-03-17 17:22:54,788 - INFO - Starting TCP Server Service...
2025-03-17 17:22:54,792 - ERROR - Unhandled exception: Configured file path does not exist: ${LINUX_PATH}
Traceback (most recent call last):
  File "/home/ruby/project/server.py", line 486, in <module>
    main()
  File "/home/ruby/project/server.py", line 445, in main
    config = ServerConfig(config_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ruby/project/server.py", line 61, in __init__
    self.validate_file_path(self.file_path)
  File "/home/ruby/project/server.py", line 104, in validate_file_path
    raise FileNotFoundError(f"Configured file path does not exist: {file_path}")
FileNotFoundError: Configured file path does not exist: ${LINUX_PATH}
2025-03-17 17:22:59,640 - INFO - Starting TCP Server Service...
2025-03-17 17:22:59,645 - ERROR - Unhandled exception: Configured file path does not exist: ${LINUX_PATH}
Traceback (most recent call last):
  File "/home/ruby/project/server.py", line 486, in <module>
    main()
  File "/home/ruby/project/server.py", line 445, in main
    config = ServerConfig(config_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ruby/project/server.py", line 61, in __init__
    self.validate_file_path(self.file_path)
  File "/home/ruby/project/server.py", line 104, in validate_file_path
    raise FileNotFoundError(f"Configured file path does not exist: {file_path}")
FileNotFoundError: Configured file path does not exist: ${LINUX_PATH}
2025-03-17 17:24:10,283 - INFO - Starting TCP Server Service...
2025-03-17 17:24:10,293 - ERROR - Unhandled exception: [Errno 13] Permission denied: '/tmp/my_server.log'
Traceback (most recent call last):
  File "/home/ruby/project/server.py", line 486, in <module>
    main()
  File "/home/ruby/project/server.py", line 453, in main
    daemon.start()
  File "/home/ruby/project/server.py", line 380, in start
    self.daemonize()
  File "/home/ruby/project/server.py", line 352, in daemonize
    with open(self.logfile, 'a+') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/tmp/my_server.log'
2025-03-17 17:24:43,000 - INFO - Starting TCP Server Service...
2025-03-17 17:24:43,001 - ERROR - Unhandled exception: CONFIG_PATH environment variable must be set.
Traceback (most recent call last):
  File "/home/ruby/project/server.py", line 486, in <module>
    main()
  File "/home/ruby/project/server.py", line 444, in main
    raise ValueError("CONFIG_PATH environment variable must be set.")
ValueError: CONFIG_PATH environment variable must be set.
2025-03-17 17:31:09,033 - INFO - Starting TCP Server Service...
2025-03-17 17:31:09,034 - ERROR - Unhandled exception: Configuration error: No section: 'SERVER'
Traceback (most recent call last):
  File "/home/ruby/project/server.py", line 85, in _read_config
    file_path = os.environ.get("LINUX_PATH") or config.get("SERVER", "linuxpath")
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/configparser.py", line 759, in get
    d = self._unify_values(section, vars)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/configparser.py", line 1132, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'SERVER'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ruby/project/server.py", line 486, in <module>
    main()
  File "/home/ruby/project/server.py", line 445, in main
    config = ServerConfig(config_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ruby/project/server.py", line 59, in __init__
    self.file_path, self.reread_on_query, self.use_ssl, self.logfile = self._read_config(config_path)
                                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ruby/project/server.py", line 93, in _read_config
    raise ConfigError(f"Configuration error: {e}") from e
ConfigError: Configuration error: No section: 'SERVER'
2025-03-18 03:06:33,308 - INFO - Starting TCP Server Service...
2025-03-18 03:06:33,337 - ERROR - Unhandled exception: [Errno 13] Permission denied: '/tmp/my_server.log'
Traceback (most recent call last):
  File "/home/ruby/project/server.py", line 486, in <module>
    main()
  File "/home/ruby/project/server.py", line 453, in main
    daemon.start()
  File "/home/ruby/project/server.py", line 380, in start
    self.daemonize()
  File "/home/ruby/project/server.py", line 352, in daemonize
    with open(self.logfile, 'a+') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/tmp/my_server.log'
2025-03-18 03:08:12,513 - INFO - Starting TCP Server Service...
2025-03-18 03:08:12,544 - ERROR - Unhandled exception: [Errno 13] Permission denied: '/tmp/my_server.log'
Traceback (most recent call last):
  File "/home/ruby/project/server.py", line 486, in <module>
    main()
  File "/home/ruby/project/server.py", line 453, in main
    daemon.start()
  File "/home/ruby/project/server.py", line 380, in start
    self.daemonize()
  File "/home/ruby/project/server.py", line 352, in daemonize
    with open(self.logfile, 'a+') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/tmp/my_server.log'
2025-03-18 03:11:12,910 - INFO - Starting TCP Server Service...
2025-03-18 03:11:12,924 - ERROR - Unhandled exception: [Errno 13] Permission denied: '/tmp/my_server.log'
Traceback (most recent call last):
  File "/home/ruby/project/server.py", line 486, in <module>
    main()
  File "/home/ruby/project/server.py", line 453, in main
    daemon.start()
  File "/home/ruby/project/server.py", line 380, in start
    self.daemonize()
  File "/home/ruby/project/server.py", line 352, in daemonize
    with open(self.logfile, 'a+') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/tmp/my_server.log'
2025-03-18 03:23:51,156 - INFO - Server interrupted by keyboard, exiting...
2025-03-18 03:23:54,042 - INFO - Starting TCP Server Service...
2025-03-18 03:23:54,079 - INFO - Creating SSL context...
2025-03-18 03:23:54,080 - INFO - Server started on ('0.0.0.0', 44445)
2025-03-18 03:23:54,080 - INFO - Server is running...
2025-03-18 03:24:02,925 - INFO - Client connected: ('127.0.0.1', 65499)
2025-03-18 03:24:02,929 - INFO - Request from client ('127.0.0.1', 65499): hello
2025-03-18 03:24:03,390 - INFO - Starting TCP Server Service...
2025-03-18 03:24:03,394 - INFO - Response Time: 0.4647 seconds
2025-03-18 03:24:03,394 - INFO - Response sent to client: ('127.0.0.1', 65499)
2025-03-18 03:24:03,394 - INFO - Connection closed for client: ('127.0.0.1', 65499)
2025-03-18 03:24:04,405 - INFO - Memory Usage: 79.5%
2025-03-18 03:24:04,406 - INFO - CPU Usage: 30.4%
2025-03-18 03:24:04,407 - INFO - Total Requests: 1, Successful Requests: 1, Failed Requests: 0
2025-03-18 03:24:09,124 - INFO - Client connected: ('127.0.0.1', 65516)
2025-03-18 03:24:09,127 - INFO - Request from client ('127.0.0.1', 65516): hello world
2025-03-18 03:24:09,138 - INFO - Response Time: 0.0099 seconds
2025-03-18 03:24:09,139 - INFO - Response sent to client: ('127.0.0.1', 65516)
2025-03-18 03:24:09,139 - INFO - Connection closed for client: ('127.0.0.1', 65516)
2025-03-18 03:24:10,171 - INFO - Memory Usage: 79.5%
2025-03-18 03:24:10,171 - INFO - CPU Usage: 47.7%
2025-03-18 03:24:10,172 - INFO - Total Requests: 2, Successful Requests: 2, Failed Requests: 0
2025-03-18 03:24:50,625 - INFO - Server interrupted by keyboard, exiting...
2025-03-18 14:26:33,071 - INFO - Starting TCP Server Service...
2025-03-18 14:26:33,142 - INFO - Creating SSL context...
2025-03-18 14:26:33,142 - INFO - Server started on ('0.0.0.0', 44445)
2025-03-18 14:26:33,142 - INFO - Server is running...
2025-03-18 14:27:07,248 - INFO - Client connected: ('127.0.0.1', 58323)
2025-03-18 14:27:07,250 - INFO - Request from client ('127.0.0.1', 58323): your query string
2025-03-18 14:27:07,517 - INFO - Starting TCP Server Service...
2025-03-18 14:27:07,520 - INFO - Response Time: 0.2707 seconds
2025-03-18 14:27:07,520 - INFO - Response sent to client: ('127.0.0.1', 58323)
2025-03-18 14:27:07,520 - INFO - Connection closed for client: ('127.0.0.1', 58323)
2025-03-18 14:27:07,521 - ERROR - Unhandled exception in client_connected_cb
transport: <asyncio.sslproto._SSLProtocolTransport object at 0x00000224EF4DF3B0>
Traceback (most recent call last):
  File "C:\Python312\Lib\asyncio\windows_events.py", line 462, in finish_socket_func
    return ov.getresult()
           ^^^^^^^^^^^^^^
OSError: [WinError 64] The specified network name is no longer available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ADMIN\Desktop\Standard Introductory Test Task\server.py", line 244, in handle_client
    await writer.wait_closed()
  File "C:\Python312\Lib\asyncio\streams.py", line 364, in wait_closed
    await self._protocol._get_close_waiter(self)
  File "C:\Python312\Lib\asyncio\proactor_events.py", line 286, in _loop_reading
    length = fut.result()
             ^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\windows_events.py", line 803, in _poll
    value = callback(transferred, key, ov)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\windows_events.py", line 466, in finish_socket_func
    raise ConnectionResetError(*exc.args)
ConnectionResetError: [WinError 64] The specified network name is no longer available
2025-03-18 14:27:20,646 - ERROR - Unhandled exception in client_connected_cb
transport: <asyncio.sslproto._SSLProtocolTransport object at 0x00000224EF5AC650>
Traceback (most recent call last):
  File "C:\Users\ADMIN\Desktop\Standard Introductory Test Task\server.py", line 162, in handle_client
    pr.enable()
ValueError: Another profiling tool is already active
2025-03-18 14:27:28,499 - ERROR - Unhandled exception in client_connected_cb
transport: <asyncio.sslproto._SSLProtocolTransport object at 0x00000224EF5ACB30>
Traceback (most recent call last):
  File "C:\Users\ADMIN\Desktop\Standard Introductory Test Task\server.py", line 162, in handle_client
    pr.enable()
ValueError: Another profiling tool is already active
2025-03-18 14:33:39,372 - INFO - Server interrupted by keyboard, exiting...
2025-03-18 14:33:47,214 - INFO - Starting TCP Server Service...
2025-03-18 14:33:47,222 - INFO - Creating SSL context...
2025-03-18 14:33:47,222 - INFO - Server started on ('0.0.0.0', 44445)
2025-03-18 14:33:47,222 - INFO - Server is running...
2025-03-18 14:33:52,845 - INFO - Client connected: ('127.0.0.1', 58386)
2025-03-18 14:33:52,846 - INFO - Request from client ('127.0.0.1', 58386): hello world
2025-03-18 14:33:53,131 - INFO - Starting TCP Server Service...
2025-03-18 14:33:53,134 - INFO - Response Time: 0.2874 seconds
2025-03-18 14:33:53,134 - INFO - Response sent to client: ('127.0.0.1', 58386)
2025-03-18 14:33:53,134 - INFO - Connection closed for client: ('127.0.0.1', 58386)
2025-03-18 14:33:54,145 - INFO - Memory Usage: 86.4%
2025-03-18 14:33:54,145 - INFO - CPU Usage: 10.8%
2025-03-18 14:33:54,146 - INFO - Total Requests: 1, Successful Requests: 1, Failed Requests: 0
2025-03-18 14:34:35,569 - INFO - Client connected: ('127.0.0.1', 58395)
2025-03-18 14:34:35,569 - INFO - Request from client ('127.0.0.1', 58395): hello
2025-03-18 14:34:35,571 - INFO - Response Time: 0.0016 seconds
2025-03-18 14:34:35,571 - INFO - Response sent to client: ('127.0.0.1', 58395)
2025-03-18 14:34:35,571 - INFO - Connection closed for client: ('127.0.0.1', 58395)
2025-03-18 14:34:36,577 - INFO - Memory Usage: 86.3%
2025-03-18 14:34:36,577 - INFO - CPU Usage: 9.4%
2025-03-18 14:34:36,577 - INFO - Total Requests: 2, Successful Requests: 2, Failed Requests: 0
2025-03-18 14:34:53,499 - INFO - Client connected: ('127.0.0.1', 58399)
2025-03-18 14:34:53,500 - INFO - Request from client ('127.0.0.1', 58399): hello there
2025-03-18 14:34:53,503 - INFO - Response Time: 0.0030 seconds
2025-03-18 14:34:53,504 - INFO - Response sent to client: ('127.0.0.1', 58399)
2025-03-18 14:34:53,504 - INFO - Connection closed for client: ('127.0.0.1', 58399)
2025-03-18 14:34:54,517 - INFO - Memory Usage: 86.3%
2025-03-18 14:34:54,518 - INFO - CPU Usage: 10.1%
2025-03-18 14:34:54,518 - INFO - Total Requests: 3, Successful Requests: 3, Failed Requests: 0
2025-03-18 14:35:23,153 - INFO - Server interrupted by keyboard, exiting...
2025-03-18 15:02:49,521 - INFO - Starting TCP Server Service...
2025-03-18 15:02:49,572 - INFO - Creating SSL context...
2025-03-18 15:02:49,575 - INFO - Server started on ('0.0.0.0', 44445)
2025-03-18 15:02:49,575 - INFO - Server is running...
2025-03-18 15:03:01,008 - INFO - Client connected: ('127.0.0.1', 58737)
2025-03-18 15:03:01,010 - INFO - Request from client ('127.0.0.1', 58737): hello there
2025-03-18 15:03:01,291 - INFO - Starting TCP Server Service...
2025-03-18 15:03:01,294 - INFO - Response Time: 0.2834 seconds
2025-03-18 15:03:01,294 - INFO - Response sent to client: ('127.0.0.1', 58737)
2025-03-18 15:03:01,294 - INFO - Connection closed for client: ('127.0.0.1', 58737)
2025-03-18 15:03:02,305 - INFO - Memory Usage: 88.0%
2025-03-18 15:03:02,305 - INFO - CPU Usage: 9.3%
2025-03-18 15:03:02,305 - INFO - Total Requests: 1, Successful Requests: 1, Failed Requests: 0
2025-03-18 15:03:12,625 - INFO - Server interrupted by keyboard, exiting...
2025-03-18 15:11:50,810 - INFO - Starting TCP Server Service...
2025-03-18 15:11:50,814 - ERROR - Unhandled exception: Configured file path does not exist: ${LINUX_PATH}
Traceback (most recent call last):
  File "/mnt/c/Users/ADMIN/Desktop/Standard Introductory Test Task/server.py", line 486, in <module>
    main()
  File "/mnt/c/Users/ADMIN/Desktop/Standard Introductory Test Task/server.py", line 445, in main
    config = ServerConfig(config_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/ADMIN/Desktop/Standard Introductory Test Task/server.py", line 62, in __init__
    self.validate_file_path(self.file_path)
  File "/mnt/c/Users/ADMIN/Desktop/Standard Introductory Test Task/server.py", line 105, in validate_file_path
    raise FileNotFoundError(f"Configured file path does not exist: {file_path}")
FileNotFoundError: Configured file path does not exist: ${LINUX_PATH}
2025-03-18 15:15:41,993 - INFO - Starting TCP Server Service...
2025-03-18 15:15:41,997 - ERROR - Unhandled exception: Configured file path does not exist: ${LINUX_PATH}
Traceback (most recent call last):
  File "/mnt/c/Users/ADMIN/Desktop/Standard Introductory Test Task/server.py", line 486, in <module>
    main()
  File "/mnt/c/Users/ADMIN/Desktop/Standard Introductory Test Task/server.py", line 445, in main
    config = ServerConfig(config_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/ADMIN/Desktop/Standard Introductory Test Task/server.py", line 62, in __init__
    self.validate_file_path(self.file_path)
  File "/mnt/c/Users/ADMIN/Desktop/Standard Introductory Test Task/server.py", line 105, in validate_file_path
    raise FileNotFoundError(f"Configured file path does not exist: {file_path}")
FileNotFoundError: Configured file path does not exist: ${LINUX_PATH}
2025-03-18 15:21:19,355 - INFO - Starting TCP Server Service...
2025-03-18 15:21:29,498 - INFO - Starting TCP Server Service...
2025-03-18 15:21:29,524 - CRITICAL - Unexpected error occurred while starting the server: CERT_PATH environment variable must be set.
2025-03-18 15:27:48,658 - INFO - Starting TCP Server Service...
2025-03-18 15:27:48,680 - CRITICAL - Unexpected error occurred while starting the server: KEY_PATH environment variable must be set.
2025-03-18 15:29:09,201 - INFO - Starting TCP Server Service...
2025-03-18 15:29:09,243 - INFO - Creating SSL context...
2025-03-18 15:29:09,244 - INFO - Server started on ('0.0.0.0', 44445)
2025-03-18 15:29:09,244 - INFO - Server is running...
2025-03-18 15:29:28,855 - INFO - Client connected: ('127.0.0.1', 37624)
2025-03-18 15:29:28,856 - INFO - Request from client ('127.0.0.1', 37624): example search
2025-03-18 15:29:29,016 - INFO - Starting TCP Server Service...
2025-03-18 15:29:29,019 - INFO - Response Time: 0.1619 seconds
2025-03-18 15:29:29,019 - INFO - Response sent to client: ('127.0.0.1', 37624)
2025-03-18 15:29:29,019 - INFO - Connection closed for client: ('127.0.0.1', 37624)
2025-03-18 15:29:30,031 - INFO - Memory Usage: 16.2%
2025-03-18 15:29:30,032 - INFO - CPU Usage: 0.0%
2025-03-18 15:29:30,032 - INFO - Total Requests: 1, Successful Requests: 1, Failed Requests: 0
2025-03-18 16:20:51,263 - INFO - Client connected: ('127.0.0.1', 57936)
2025-03-18 16:20:51,267 - INFO - Request from client ('127.0.0.1', 57936): hello there
2025-03-18 16:20:51,281 - INFO - Response Time: 0.0140 seconds
2025-03-18 16:20:51,282 - INFO - Response sent to client: ('127.0.0.1', 57936)
2025-03-18 16:20:51,282 - INFO - Connection closed for client: ('127.0.0.1', 57936)
2025-03-18 16:20:52,299 - INFO - Memory Usage: 16.9%
2025-03-18 16:20:52,299 - INFO - CPU Usage: 5.2%
2025-03-18 16:20:52,300 - INFO - Total Requests: 2, Successful Requests: 2, Failed Requests: 0
2025-03-18 16:21:18,336 - INFO - Client connected: ('127.0.0.1', 49900)
2025-03-18 16:21:18,337 - INFO - Request from client ('127.0.0.1', 49900): hello world
2025-03-18 16:21:18,340 - INFO - Response Time: 0.0031 seconds
2025-03-18 16:21:18,341 - INFO - Response sent to client: ('127.0.0.1', 49900)
2025-03-18 16:21:18,341 - INFO - Connection closed for client: ('127.0.0.1', 49900)
2025-03-18 16:21:19,345 - INFO - Memory Usage: 16.9%
2025-03-18 16:21:19,346 - INFO - CPU Usage: 5.4%
2025-03-18 16:21:19,347 - INFO - Total Requests: 3, Successful Requests: 3, Failed Requests: 0
2025-03-19 15:15:14,755 - INFO - Starting TCP Server Service...
2025-03-19 15:15:14,755 - ERROR - Unhandled exception: CONFIG_PATH environment variable must be set.
Traceback (most recent call last):
  File "C:\Users\ADMIN\Desktop\Standard Introductory Test Task\server.py", line 472, in <module>
    raise ValueError("CONFIG_PATH environment variable must be set.")
ValueError: CONFIG_PATH environment variable must be set.
2025-03-19 15:15:19,523 - INFO - Starting TCP Server Service...
2025-03-19 15:15:19,523 - ERROR - Unhandled exception: CONFIG_PATH environment variable must be set.
Traceback (most recent call last):
  File "C:\Users\ADMIN\Desktop\Standard Introductory Test Task\server.py", line 472, in <module>
    raise ValueError("CONFIG_PATH environment variable must be set.")
ValueError: CONFIG_PATH environment variable must be set.
2025-03-19 15:15:37,974 - INFO - Starting TCP Server Service...
2025-03-19 15:16:09,505 - INFO - Client connected: ('127.0.0.1', 41886)
2025-03-19 15:16:09,521 - INFO - Request from client ('127.0.0.1', 41886): hello world
2025-03-19 15:16:09,584 - INFO - Response Time: 0.0622 seconds
2025-03-19 15:16:09,585 - INFO - Response sent to client: ('127.0.0.1', 41886)
2025-03-19 15:16:09,585 - INFO - Connection closed for client: ('127.0.0.1', 41886)
2025-03-19 15:16:10,620 - INFO - Memory Usage: 19.5%
2025-03-19 15:16:10,623 - INFO - CPU Usage: 0.2%
2025-03-19 15:16:10,624 - INFO - Total Requests: 4, Successful Requests: 4, Failed Requests: 0
2025-03-19 15:29:53,464 - INFO - Client connected: ('127.0.0.1', 39972)
2025-03-19 15:29:53,466 - INFO - Request from client ('127.0.0.1', 39972): hello there
2025-03-19 15:29:53,479 - INFO - Response Time: 0.0123 seconds
2025-03-19 15:29:53,480 - INFO - Response sent to client: ('127.0.0.1', 39972)
2025-03-19 15:29:53,480 - INFO - Connection closed for client: ('127.0.0.1', 39972)
2025-03-19 15:29:54,491 - INFO - Memory Usage: 19.1%
2025-03-19 15:29:54,491 - INFO - CPU Usage: 0.0%
2025-03-19 15:29:54,491 - INFO - Total Requests: 5, Successful Requests: 5, Failed Requests: 0
2025-03-19 16:01:14,345 - INFO - Client connected: ('127.0.0.1', 15262)
2025-03-19 16:01:14,349 - INFO - Request from client ('127.0.0.1', 15262): hello world
2025-03-19 16:01:14,362 - INFO - Response Time: 0.0124 seconds
2025-03-19 16:01:14,362 - INFO - Response sent to client: ('127.0.0.1', 15262)
2025-03-19 16:01:14,363 - INFO - Connection closed for client: ('127.0.0.1', 15262)
2025-03-19 16:01:15,380 - INFO - Memory Usage: 19.7%
2025-03-19 16:01:15,380 - INFO - CPU Usage: 0.0%
2025-03-19 16:01:15,380 - INFO - Total Requests: 6, Successful Requests: 6, Failed Requests: 0
2025-03-19 16:01:32,513 - INFO - Client connected: ('127.0.0.1', 59302)
2025-03-19 16:01:32,515 - INFO - Request from client ('127.0.0.1', 59302): This is my test string
2025-03-19 16:01:32,521 - INFO - Response Time: 0.0048 seconds
2025-03-19 16:01:32,523 - INFO - Response sent to client: ('127.0.0.1', 59302)
2025-03-19 16:01:32,525 - INFO - Connection closed for client: ('127.0.0.1', 59302)
2025-03-19 16:01:33,533 - INFO - Memory Usage: 19.7%
2025-03-19 16:01:33,534 - INFO - CPU Usage: 0.3%
2025-03-19 16:01:33,534 - INFO - Total Requests: 7, Successful Requests: 7, Failed Requests: 0
2025-03-19 16:02:46,638 - INFO - Client connected: ('127.0.0.1', 65026)
2025-03-19 16:02:46,641 - INFO - Request from client ('127.0.0.1', 65026): hello there
2025-03-19 16:02:46,650 - INFO - Response Time: 0.0093 seconds
2025-03-19 16:02:46,651 - INFO - Response sent to client: ('127.0.0.1', 65026)
2025-03-19 16:02:46,652 - INFO - Connection closed for client: ('127.0.0.1', 65026)
2025-03-19 16:02:47,659 - INFO - Memory Usage: 19.4%
2025-03-19 16:02:47,659 - INFO - CPU Usage: 0.0%
2025-03-19 16:02:47,660 - INFO - Total Requests: 8, Successful Requests: 8, Failed Requests: 0
2025-03-19 16:02:56,080 - INFO - Client connected: ('127.0.0.1', 65034)
2025-03-19 16:02:56,081 - INFO - Request from client ('127.0.0.1', 65034): hello world
2025-03-19 16:02:56,089 - INFO - Response Time: 0.0067 seconds
2025-03-19 16:02:56,089 - INFO - Response sent to client: ('127.0.0.1', 65034)
2025-03-19 16:02:56,090 - INFO - Connection closed for client: ('127.0.0.1', 65034)
2025-03-19 16:02:57,096 - INFO - Memory Usage: 19.4%
2025-03-19 16:02:57,096 - INFO - CPU Usage: 0.0%
2025-03-19 16:02:57,097 - INFO - Total Requests: 9, Successful Requests: 9, Failed Requests: 0
2025-03-19 16:08:38,339 - INFO - Client connected: ('127.0.0.1', 31282)
2025-03-19 16:08:38,340 - INFO - Request from client ('127.0.0.1', 31282): This is my test string
2025-03-19 16:08:38,343 - INFO - Response Time: 0.0030 seconds
2025-03-19 16:08:38,343 - INFO - Response sent to client: ('127.0.0.1', 31282)
2025-03-19 16:08:38,344 - INFO - Connection closed for client: ('127.0.0.1', 31282)
2025-03-19 16:08:39,349 - INFO - Memory Usage: 19.2%
2025-03-19 16:08:39,350 - INFO - CPU Usage: 0.2%
2025-03-19 16:08:39,350 - INFO - Total Requests: 10, Successful Requests: 10, Failed Requests: 0
2025-03-19 16:08:48,078 - INFO - Client connected: ('127.0.0.1', 43056)
2025-03-19 16:08:48,078 - INFO - Request from client ('127.0.0.1', 43056): hi
2025-03-19 16:08:48,082 - INFO - Response Time: 0.0029 seconds
2025-03-19 16:08:48,082 - INFO - Response sent to client: ('127.0.0.1', 43056)
2025-03-19 16:08:48,082 - INFO - Connection closed for client: ('127.0.0.1', 43056)
2025-03-19 16:08:49,087 - INFO - Memory Usage: 19.5%
2025-03-19 16:08:49,088 - INFO - CPU Usage: 3.8%
2025-03-19 16:08:49,088 - INFO - Total Requests: 11, Successful Requests: 11, Failed Requests: 0
2025-03-19 16:09:04,021 - INFO - Starting TCP Server Service...
2025-03-19 16:09:04,041 - INFO - Shutting down server...
2025-03-19 16:09:04,042 - INFO - Server connections closed.
2025-03-19 16:09:04,042 - INFO - Shutting down executor...
2025-03-19 16:09:04,253 - INFO - Executor shut down successfully.
2025-03-19 16:09:04,261 - INFO - Server shut down successfully.
2025-03-19 16:09:04,261 - INFO - Memory-mapped file closed.
2025-03-19 16:09:04,262 - INFO - Final Total Requests: 11
2025-03-19 16:09:04,262 - INFO - Final Successful Requests: 11
2025-03-19 16:09:04,262 - INFO - Final Failed Requests: 0
2025-03-19 16:09:09,952 - INFO - Starting TCP Server Service...
2025-03-19 16:09:10,018 - INFO - Creating SSL context...
2025-03-19 16:09:10,019 - INFO - Server started on ('0.0.0.0', 44445)
2025-03-19 16:09:10,019 - INFO - Server is running...
2025-03-19 16:09:42,714 - INFO - Client connected: ('127.0.0.1', 40516)
2025-03-19 16:09:42,715 - INFO - Request from client ('127.0.0.1', 40516): hi
2025-03-19 16:09:42,874 - INFO - Starting TCP Server Service...
2025-03-19 16:09:42,878 - ERROR - Unexpected error handling client ('127.0.0.1', 40516): [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/mnt/c/Users/ADMIN/Desktop/Standard Introductory Test Task/server.py", line 229, in handle_client
    await writer.drain()
  File "/usr/lib/python3.12/asyncio/streams.py", line 380, in drain
    raise exc
  File "/usr/lib/python3.12/asyncio/selector_events.py", line 988, in _read_ready__get_buffer
    nbytes = self._sock.recv_into(buf)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
2025-03-19 16:09:42,883 - ERROR - Unhandled exception in client_connected_cb
transport: <asyncio.sslproto._SSLProtocolTransport object at 0x7f0e307b3050>
Traceback (most recent call last):
  File "/mnt/c/Users/ADMIN/Desktop/Standard Introductory Test Task/server.py", line 249, in handle_client
    await writer.wait_closed()
  File "/usr/lib/python3.12/asyncio/streams.py", line 364, in wait_closed
    await self._protocol._get_close_waiter(self)
  File "/usr/lib/python3.12/asyncio/selector_events.py", line 988, in _read_ready__get_buffer
    nbytes = self._sock.recv_into(buf)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
2025-03-19 16:10:49,401 - INFO - Starting TCP Server Service...
2025-03-19 16:10:49,406 - INFO - Shutting down server...
2025-03-19 16:10:49,406 - INFO - Server connections closed.
2025-03-19 16:10:49,407 - INFO - Shutting down executor...
2025-03-19 16:10:49,445 - INFO - Executor shut down successfully.
2025-03-19 16:10:49,445 - INFO - Server shut down successfully.
2025-03-19 16:10:49,446 - INFO - Memory-mapped file closed.
2025-03-19 16:10:49,447 - INFO - Final Total Requests: 1
2025-03-19 16:10:49,447 - INFO - Final Successful Requests: 0
2025-03-19 16:10:49,447 - INFO - Final Failed Requests: 1
2025-03-19 16:11:00,584 - INFO - Starting TCP Server Service...
2025-03-19 16:11:00,619 - INFO - Creating SSL context...
2025-03-19 16:11:00,621 - INFO - Server started on ('0.0.0.0', 44445)
2025-03-19 16:11:00,622 - INFO - Server is running...
2025-03-19 16:11:22,651 - INFO - Client connected: ('127.0.0.1', 13670)
2025-03-19 16:11:22,653 - INFO - Request from client ('127.0.0.1', 13670): hi
2025-03-19 16:11:22,803 - INFO - Starting TCP Server Service...
2025-03-19 16:11:22,806 - INFO - Response Time: 0.1532 seconds
2025-03-19 16:11:22,807 - INFO - Response sent to client: ('127.0.0.1', 13670)
2025-03-19 16:11:22,807 - INFO - Connection closed for client: ('127.0.0.1', 13670)
2025-03-19 16:11:23,818 - INFO - Memory Usage: 19.5%
2025-03-19 16:11:23,819 - INFO - CPU Usage: 0.0%
2025-03-19 16:11:23,819 - INFO - Total Requests: 1, Successful Requests: 1, Failed Requests: 0
2025-03-19 16:16:33,180 - INFO - Starting TCP Server Service...
2025-03-19 16:16:33,185 - INFO - Shutting down server...
2025-03-19 16:16:33,186 - INFO - Server connections closed.
2025-03-19 16:16:33,186 - INFO - Shutting down executor...
2025-03-19 16:16:33,225 - INFO - Executor shut down successfully.
2025-03-19 16:16:33,226 - INFO - Server shut down successfully.
2025-03-19 16:16:33,227 - INFO - Memory-mapped file closed.
2025-03-19 16:16:33,227 - INFO - Final Total Requests: 1
2025-03-19 16:16:33,228 - INFO - Final Successful Requests: 1
2025-03-19 16:16:33,228 - INFO - Final Failed Requests: 0
2025-03-19 16:16:54,281 - INFO - Starting TCP Server Service...
2025-03-19 16:16:54,318 - INFO - Creating SSL context...
2025-03-19 16:16:54,319 - INFO - Server started on ('0.0.0.0', 44445)
2025-03-19 16:16:54,320 - INFO - Server is running...
2025-03-19 16:17:08,252 - INFO - Client connected: ('127.0.0.1', 12470)
2025-03-19 16:17:08,253 - ERROR - Unexpected error handling client ('127.0.0.1', 12470): [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/mnt/c/Users/ADMIN/Desktop/Standard Introductory Test Task/server.py", line 196, in handle_client
    data = await reader.read(1024)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/streams.py", line 713, in read
    await self._wait_for_data('read')
  File "/usr/lib/python3.12/asyncio/streams.py", line 545, in _wait_for_data
    await self._waiter
  File "/usr/lib/python3.12/asyncio/selector_events.py", line 988, in _read_ready__get_buffer
    nbytes = self._sock.recv_into(buf)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
2025-03-19 16:17:08,257 - ERROR - Unhandled exception in client_connected_cb
transport: <asyncio.sslproto._SSLProtocolTransport object at 0x7efffbd330b0>
Traceback (most recent call last):
  File "/mnt/c/Users/ADMIN/Desktop/Standard Introductory Test Task/server.py", line 249, in handle_client
    await writer.wait_closed()
  File "/usr/lib/python3.12/asyncio/streams.py", line 364, in wait_closed
    await self._protocol._get_close_waiter(self)
  File "/usr/lib/python3.12/asyncio/selector_events.py", line 988, in _read_ready__get_buffer
    nbytes = self._sock.recv_into(buf)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
2025-03-19 16:17:17,965 - ERROR - Unhandled exception in client_connected_cb
transport: <asyncio.sslproto._SSLProtocolTransport object at 0x7efffbd72b70>
Traceback (most recent call last):
  File "/mnt/c/Users/ADMIN/Desktop/Standard Introductory Test Task/server.py", line 167, in handle_client
    pr.enable()
ValueError: Another profiling tool is already active
2025-03-19 16:38:16,556 - INFO - Starting TCP Server Service...
2025-03-19 16:38:16,560 - INFO - Shutting down server...
2025-03-19 16:38:16,561 - INFO - Server connections closed.
2025-03-19 16:38:16,562 - INFO - Shutting down executor...
2025-03-19 16:38:16,563 - INFO - Executor shut down successfully.
2025-03-19 16:38:16,563 - INFO - Server shut down successfully.
2025-03-19 16:38:16,563 - INFO - Final Total Requests: 1
2025-03-19 16:38:16,564 - INFO - Final Successful Requests: 0
2025-03-19 16:38:16,564 - INFO - Final Failed Requests: 1
2025-03-19 16:38:20,801 - INFO - Starting TCP Server Service...
2025-03-19 16:38:20,841 - INFO - Creating SSL context...
2025-03-19 16:38:20,842 - INFO - Server started on ('0.0.0.0', 44445)
2025-03-19 16:38:20,843 - INFO - Server is running...
2025-03-19 16:38:32,278 - INFO - Client connected: ('127.0.0.1', 18922)
2025-03-19 16:38:32,279 - INFO - Request from client ('127.0.0.1', 18922): hello
2025-03-19 16:38:32,435 - INFO - Starting TCP Server Service...
2025-03-19 16:38:32,438 - INFO - Response Time: 0.1584 seconds
2025-03-19 16:38:32,439 - INFO - Response sent to client: ('127.0.0.1', 18922)
2025-03-19 16:38:32,439 - INFO - Connection closed for client: ('127.0.0.1', 18922)
2025-03-19 16:38:33,450 - INFO - Memory Usage: 19.4%
2025-03-19 16:38:33,450 - INFO - CPU Usage: 0.0%
2025-03-19 16:38:33,451 - INFO - Total Requests: 1, Successful Requests: 1, Failed Requests: 0
2025-03-19 16:38:40,376 - INFO - Client connected: ('127.0.0.1', 56128)
2025-03-19 16:38:40,376 - INFO - Request from client ('127.0.0.1', 56128): hello world
2025-03-19 16:38:40,379 - INFO - Response Time: 0.0028 seconds
2025-03-19 16:38:40,380 - INFO - Response sent to client: ('127.0.0.1', 56128)
2025-03-19 16:38:40,380 - INFO - Connection closed for client: ('127.0.0.1', 56128)
2025-03-19 16:38:41,384 - INFO - Memory Usage: 19.0%
2025-03-19 16:38:41,385 - INFO - CPU Usage: 4.7%
2025-03-19 16:38:41,385 - INFO - Total Requests: 2, Successful Requests: 2, Failed Requests: 0
2025-03-20 13:49:22,440 - INFO - Client connected: ('127.0.0.1', 64752)
2025-03-20 13:49:22,470 - INFO - Request from client ('127.0.0.1', 64752): hello world
2025-03-20 13:49:22,563 - INFO - Response Time: 0.0923 seconds
2025-03-20 13:49:22,563 - INFO - Response sent to client: ('127.0.0.1', 64752)
2025-03-20 13:49:22,564 - INFO - Connection closed for client: ('127.0.0.1', 64752)
2025-03-20 13:49:23,606 - INFO - Memory Usage: 21.5%
2025-03-20 13:49:23,607 - INFO - CPU Usage: 0.0%
2025-03-20 13:49:23,607 - INFO - Total Requests: 3, Successful Requests: 3, Failed Requests: 0
2025-03-20 13:49:50,126 - INFO - Client connected: ('127.0.0.1', 21538)
2025-03-20 13:49:50,127 - INFO - Request from client ('127.0.0.1', 21538): test samples
2025-03-20 13:49:50,131 - INFO - Response Time: 0.0043 seconds
2025-03-20 13:49:50,132 - INFO - Response sent to client: ('127.0.0.1', 21538)
2025-03-20 13:49:50,132 - INFO - Connection closed for client: ('127.0.0.1', 21538)
2025-03-20 13:49:51,136 - INFO - Memory Usage: 20.9%
2025-03-20 13:49:51,137 - INFO - CPU Usage: 4.0%
2025-03-20 13:49:51,138 - INFO - Total Requests: 4, Successful Requests: 4, Failed Requests: 0
2025-03-20 13:50:27,175 - INFO - Client connected: ('127.0.0.1', 54658)
2025-03-20 13:50:27,176 - INFO - Request from client ('127.0.0.1', 54658): another entry
2025-03-20 13:50:27,181 - INFO - Response Time: 0.0038 seconds
2025-03-20 13:50:27,181 - INFO - Response sent to client: ('127.0.0.1', 54658)
2025-03-20 13:50:27,182 - INFO - Connection closed for client: ('127.0.0.1', 54658)
2025-03-20 13:50:28,193 - INFO - Memory Usage: 21.4%
2025-03-20 13:50:28,194 - INFO - CPU Usage: 2.5%
2025-03-20 13:50:28,194 - INFO - Total Requests: 5, Successful Requests: 5, Failed Requests: 0
2025-03-20 14:46:42,679 - INFO - Client connected: ('127.0.0.1', 47354)
2025-03-20 14:46:42,707 - INFO - Request from client ('127.0.0.1', 47354): another entry
2025-03-20 14:46:42,824 - INFO - Response Time: 0.0889 seconds
2025-03-20 14:46:42,825 - INFO - Response sent to client: ('127.0.0.1', 47354)
2025-03-20 14:46:42,826 - INFO - Connection closed for client: ('127.0.0.1', 47354)
2025-03-20 14:46:43,848 - INFO - Memory Usage: 21.6%
2025-03-20 14:46:43,849 - INFO - CPU Usage: 2.3%
2025-03-20 14:46:43,849 - INFO - Total Requests: 6, Successful Requests: 6, Failed Requests: 0
2025-03-20 14:52:57,674 - INFO - Starting TCP Server Service...
2025-03-20 14:52:57,694 - INFO - Shutting down server...
2025-03-20 14:52:57,696 - INFO - Server connections closed.
2025-03-20 14:52:57,697 - INFO - Shutting down executor...
2025-03-20 14:52:57,968 - INFO - Executor shut down successfully.
2025-03-20 14:52:57,968 - INFO - Server shut down successfully.
2025-03-20 14:52:57,969 - INFO - Memory-mapped file closed.
2025-03-20 14:52:57,970 - INFO - Final Total Requests: 6
2025-03-20 14:52:57,970 - INFO - Final Successful Requests: 6
2025-03-20 14:52:57,970 - INFO - Final Failed Requests: 0
2025-03-20 14:53:02,906 - INFO - Starting TCP Server Service...
2025-03-20 14:53:02,964 - INFO - Creating SSL context...
2025-03-20 14:53:02,965 - INFO - Server started on ('0.0.0.0', 44445)
2025-03-20 14:53:02,965 - INFO - Server is running...
2025-03-20 14:53:11,070 - INFO - Client connected: ('127.0.0.1', 59808)
2025-03-20 14:53:11,071 - INFO - Request from client ('127.0.0.1', 59808): hello world
2025-03-20 14:53:11,220 - INFO - Starting TCP Server Service...
2025-03-20 14:53:11,223 - INFO - Response Time: 0.1515 seconds
2025-03-20 14:53:11,232 - INFO - Response sent to client: ('127.0.0.1', 59808)
2025-03-20 14:53:11,233 - INFO - Connection closed for client: ('127.0.0.1', 59808)
2025-03-20 14:53:12,240 - INFO - Memory Usage: 20.9%
2025-03-20 14:53:12,242 - INFO - CPU Usage: 0.0%
2025-03-20 14:53:12,243 - INFO - Total Requests: 1, Successful Requests: 1, Failed Requests: 0
2025-03-20 14:53:18,648 - INFO - Client connected: ('127.0.0.1', 59810)
2025-03-20 14:53:18,649 - INFO - Request from client ('127.0.0.1', 59810): hello
2025-03-20 14:53:18,653 - INFO - Response Time: 0.0034 seconds
2025-03-20 14:53:18,653 - INFO - Response sent to client: ('127.0.0.1', 59810)
2025-03-20 14:53:18,653 - INFO - Connection closed for client: ('127.0.0.1', 59810)
2025-03-20 14:53:19,659 - INFO - Memory Usage: 21.3%
2025-03-20 14:53:19,660 - INFO - CPU Usage: 0.0%
2025-03-20 14:53:19,662 - INFO - Total Requests: 2, Successful Requests: 2, Failed Requests: 0
2025-03-20 15:51:46,483 - INFO - Starting TCP Server Service...
2025-03-20 15:51:46,483 - ERROR - Unhandled exception: 'ServerConfig' object has no attribute 'file_path'
Traceback (most recent call last):
  File "/mnt/c/Users/ADMIN/Desktop/Standard Introductory Test Task/server.py", line 570, in <module>
    main()
  File "/mnt/c/Users/ADMIN/Desktop/Standard Introductory Test Task/server.py", line 522, in main
    config = ServerConfig(config_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/ADMIN/Desktop/Standard Introductory Test Task/server.py", line 59, in __init__
    self.file_path,
    ^^^^^^^^^^^^^^
AttributeError: 'ServerConfig' object has no attribute 'file_path'
2025-03-20 15:51:51,579 - INFO - Starting TCP Server Service...
2025-03-20 15:51:51,580 - ERROR - Unhandled exception: 'ServerConfig' object has no attribute 'file_path'
Traceback (most recent call last):
  File "/mnt/c/Users/ADMIN/Desktop/Standard Introductory Test Task/server.py", line 570, in <module>
    main()
  File "/mnt/c/Users/ADMIN/Desktop/Standard Introductory Test Task/server.py", line 522, in main
    config = ServerConfig(config_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/ADMIN/Desktop/Standard Introductory Test Task/server.py", line 59, in __init__
    self.file_path,
    ^^^^^^^^^^^^^^
AttributeError: 'ServerConfig' object has no attribute 'file_path'
2025-03-20 15:51:57,047 - INFO - Client connected: ('127.0.0.1', 64856)
2025-03-20 15:51:57,054 - INFO - Request from client ('127.0.0.1', 64856): hello
2025-03-20 15:51:57,081 - INFO - Response Time: 0.0258 seconds
2025-03-20 15:51:57,081 - INFO - Response sent to client: ('127.0.0.1', 64856)
2025-03-20 15:51:57,082 - INFO - Connection closed for client: ('127.0.0.1', 64856)
2025-03-20 15:51:58,104 - INFO - Memory Usage: 21.3%
2025-03-20 15:51:58,105 - INFO - CPU Usage: 0.0%
2025-03-20 15:51:58,106 - INFO - Total Requests: 3, Successful Requests: 3, Failed Requests: 0
2025-03-20 16:30:20,915 - INFO - Starting TCP Server Service...
2025-03-20 16:30:20,916 - ERROR - Unhandled exception: 'ServerConfig' object has no attribute 'file_path'
Traceback (most recent call last):
  File "/mnt/c/Users/ADMIN/Desktop/Standard Introductory Test Task/server.py", line 565, in <module>
    main()
  File "/mnt/c/Users/ADMIN/Desktop/Standard Introductory Test Task/server.py", line 517, in main
    config = ServerConfig(config_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/ADMIN/Desktop/Standard Introductory Test Task/server.py", line 56, in __init__
    self.file_path,
    ^^^^^^^^^^^^^^
AttributeError: 'ServerConfig' object has no attribute 'file_path'
2025-03-20 16:43:15,485 - ERROR - Unhandled exception: 'ServerConfig' object has no attribute 'file_path'
Traceback (most recent call last):
  File "/mnt/c/Users/ADMIN/Desktop/Standard Introductory Test Task/server.py", line 564, in <module>
    main()
  File "/mnt/c/Users/ADMIN/Desktop/Standard Introductory Test Task/server.py", line 516, in main
    config = ServerConfig(config_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/ADMIN/Desktop/Standard Introductory Test Task/server.py", line 55, in __init__
    self.file_path,
    ^^^^^^^^^^^^^^
AttributeError: 'ServerConfig' object has no attribute 'file_path'
2025-03-20 16:43:21,590 - INFO - Client connected: ('127.0.0.1', 11116)
2025-03-20 16:43:21,598 - INFO - Request from client ('127.0.0.1', 11116): hello
2025-03-20 16:43:21,628 - INFO - Response Time: 0.0295 seconds
2025-03-20 16:43:21,629 - INFO - Response sent to client: ('127.0.0.1', 11116)
2025-03-20 16:43:21,629 - INFO - Connection closed for client: ('127.0.0.1', 11116)
2025-03-20 16:43:22,650 - INFO - Memory Usage: 21.9%
2025-03-20 16:43:22,651 - INFO - CPU Usage: 0.0%
2025-03-20 16:43:22,651 - INFO - Total Requests: 4, Successful Requests: 4, Failed Requests: 0
2025-03-20 16:43:28,283 - INFO - Client connected: ('127.0.0.1', 11120)
2025-03-20 16:43:28,284 - INFO - Request from client ('127.0.0.1', 11120): hello world
2025-03-20 16:43:28,292 - INFO - Response Time: 0.0069 seconds
2025-03-20 16:43:28,292 - INFO - Response sent to client: ('127.0.0.1', 11120)
2025-03-20 16:43:28,293 - INFO - Connection closed for client: ('127.0.0.1', 11120)
2025-03-20 16:43:29,302 - INFO - Memory Usage: 21.9%
2025-03-20 16:43:29,302 - INFO - CPU Usage: 0.0%
2025-03-20 16:43:29,302 - INFO - Total Requests: 5, Successful Requests: 5, Failed Requests: 0
2025-03-21 03:03:27,744 - INFO - Creating SSL context...
2025-03-21 03:03:27,744 - INFO - Server started on ('0.0.0.0', 44445)
2025-03-21 03:03:27,744 - INFO - Server is running...
2025-03-21 03:03:46,921 - INFO - Client connected: ('127.0.0.1', 16320)
2025-03-21 03:03:46,924 - INFO - Request from client ('127.0.0.1', 16320): test
2025-03-21 03:03:47,299 - INFO - Response Time: 0.3745 seconds
2025-03-21 03:03:47,300 - INFO - Response sent to client: ('127.0.0.1', 16320)
2025-03-21 03:03:47,300 - INFO - Connection closed for client: ('127.0.0.1', 16320)
2025-03-21 03:03:48,315 - INFO - Memory Usage: 82.7%
2025-03-21 03:03:48,316 - INFO - CPU Usage: 23.0%
2025-03-21 03:03:48,316 - INFO - Total Requests: 1, Successful Requests: 1, Failed Requests: 0
2025-03-21 03:05:53,517 - INFO - Server interrupted by keyboard, exiting...
2025-03-21 03:07:29,109 - INFO - Creating SSL context...
2025-03-21 03:07:29,111 - INFO - Server started on ('0.0.0.0', 44445)
2025-03-21 03:07:29,112 - INFO - Server is running...
2025-03-21 15:46:15,670 - INFO - Creating SSL context...
2025-03-21 15:46:15,672 - INFO - Server started on ('0.0.0.0', 44445)
2025-03-21 15:46:15,672 - INFO - Server is running...
2025-03-21 15:48:23,070 - INFO - Client connected: ('127.0.0.1', 36986)
2025-03-21 15:48:23,071 - INFO - Request from client ('127.0.0.1', 36986): hello
2025-03-21 15:48:23,227 - INFO - Response Time: 0.1554 seconds
2025-03-21 15:48:23,235 - INFO - Response sent to client: ('127.0.0.1', 36986)
2025-03-21 15:48:23,236 - INFO - Connection closed for client: ('127.0.0.1', 36986)
2025-03-21 15:48:24,243 - INFO - Memory Usage: 15.6%
2025-03-21 15:48:24,243 - INFO - CPU Usage: 4.7%
2025-03-21 15:48:24,244 - INFO - Total Requests: 1, Successful Requests: 1, Failed Requests: 0
2025-03-21 15:54:21,441 - INFO - Shutting down server...
2025-03-21 15:54:21,442 - INFO - Server connections closed.
2025-03-21 15:54:21,443 - INFO - Shutting down executor...
2025-03-21 15:54:21,480 - INFO - Executor shut down successfully.
2025-03-21 15:54:21,481 - INFO - Server shut down successfully.
2025-03-21 15:54:21,481 - INFO - Memory-mapped file closed.
2025-03-21 15:54:21,481 - INFO - Final Total Requests: 1
2025-03-21 15:54:21,482 - INFO - Final Successful Requests: 1
2025-03-21 15:54:21,482 - INFO - Final Failed Requests: 0
2025-03-21 15:54:31,092 - INFO - Creating SSL context...
2025-03-21 15:54:31,093 - INFO - Server started on ('0.0.0.0', 44445)
2025-03-21 15:54:31,093 - INFO - Server is running...
2025-03-21 15:54:47,762 - INFO - Client connected: ('127.0.0.1', 35982)
2025-03-21 15:54:47,763 - INFO - Request from client ('127.0.0.1', 35982): hello world
2025-03-21 15:54:47,899 - INFO - Response Time: 0.1350 seconds
2025-03-21 15:54:47,906 - INFO - Response sent to client: ('127.0.0.1', 35982)
2025-03-21 15:54:47,906 - INFO - Connection closed for client: ('127.0.0.1', 35982)
2025-03-21 15:54:48,912 - INFO - Memory Usage: 15.7%
2025-03-21 15:54:48,913 - INFO - CPU Usage: 4.7%
2025-03-21 15:54:48,913 - INFO - Total Requests: 1, Successful Requests: 1, Failed Requests: 0
2025-03-21 16:35:26,208 - INFO - Creating SSL context...
2025-03-21 16:35:26,209 - INFO - Server started on ('0.0.0.0', 44445)
2025-03-21 16:35:26,210 - INFO - Server is running...
2025-03-21 16:36:09,381 - INFO - Client connected: ('127.0.0.1', 48566)
2025-03-21 16:36:09,382 - INFO - Request from client ('127.0.0.1', 48566): hello
2025-03-21 16:36:09,521 - INFO - Response Time: 0.1383 seconds
2025-03-21 16:36:09,528 - INFO - Response sent to client: ('127.0.0.1', 48566)
2025-03-21 16:36:09,529 - INFO - Connection closed for client: ('127.0.0.1', 48566)
2025-03-21 16:36:10,536 - INFO - Memory Usage: 15.2%
2025-03-21 16:36:10,537 - INFO - CPU Usage: 0.0%
2025-03-21 16:36:10,537 - INFO - Total Requests: 1, Successful Requests: 1, Failed Requests: 0
2025-03-21 16:36:20,860 - INFO - Shutting down server...
2025-03-21 16:36:20,860 - INFO - Server connections closed.
2025-03-21 16:36:20,861 - INFO - Shutting down executor...
2025-03-21 16:36:20,897 - INFO - Executor shut down successfully.
2025-03-21 16:36:20,898 - INFO - Server shut down successfully.
2025-03-21 16:36:20,899 - INFO - Memory-mapped file closed.
2025-03-21 16:36:20,899 - INFO - Final Total Requests: 1
2025-03-21 16:36:20,899 - INFO - Final Successful Requests: 1
2025-03-21 16:36:20,900 - INFO - Final Failed Requests: 0
2025-03-21 16:36:34,619 - INFO - Creating SSL context...
2025-03-21 16:36:34,620 - INFO - Server started on ('0.0.0.0', 44445)
2025-03-21 16:36:34,620 - INFO - Server is running...
2025-03-21 16:36:45,927 - INFO - Client connected: ('127.0.0.1', 35770)
2025-03-21 16:36:45,928 - INFO - Request from client ('127.0.0.1', 35770): hello world
2025-03-21 16:36:46,070 - INFO - Response Time: 0.1414 seconds
2025-03-21 16:36:46,078 - INFO - Response sent to client: ('127.0.0.1', 35770)
2025-03-21 16:36:46,079 - INFO - Connection closed for client: ('127.0.0.1', 35770)
2025-03-21 16:36:47,086 - INFO - Memory Usage: 15.4%
2025-03-21 16:36:47,088 - INFO - CPU Usage: 0.0%
2025-03-21 16:36:47,089 - INFO - Total Requests: 1, Successful Requests: 1, Failed Requests: 0
2025-03-21 16:52:26,005 - INFO - Shutting down server...
2025-03-21 16:52:26,005 - INFO - Server connections closed.
2025-03-21 16:52:26,005 - INFO - Shutting down executor...
2025-03-21 16:52:26,043 - INFO - Executor shut down successfully.
2025-03-21 16:52:26,043 - INFO - Server shut down successfully.
2025-03-21 16:52:26,044 - INFO - Memory-mapped file closed.
2025-03-21 16:52:26,045 - INFO - Final Total Requests: 1
2025-03-21 16:52:26,045 - INFO - Final Successful Requests: 1
2025-03-21 16:52:26,045 - INFO - Final Failed Requests: 0
2025-03-21 16:52:28,929 - INFO - Creating SSL context...
2025-03-21 16:52:28,930 - INFO - Server started on ('0.0.0.0', 44445)
2025-03-21 16:52:28,931 - INFO - Server is running...
2025-03-21 16:52:40,281 - INFO - Client connected: ('127.0.0.1', 41216)
2025-03-21 16:52:40,282 - INFO - Request from client ('127.0.0.1', 41216): hello world
2025-03-21 16:52:40,423 - INFO - Response Time: 0.1401 seconds
2025-03-21 16:52:40,423 - INFO - Response sent to client: ('127.0.0.1', 41216)
2025-03-21 16:52:40,423 - INFO - Connection closed for client: ('127.0.0.1', 41216)
2025-03-21 16:52:41,433 - INFO - Memory Usage: 15.5%
2025-03-21 16:52:41,435 - INFO - CPU Usage: 0.0%
2025-03-21 16:52:41,436 - INFO - Total Requests: 1, Successful Requests: 1, Failed Requests: 0
2025-03-21 16:55:34,106 - INFO - Creating SSL context...
2025-03-21 16:55:34,107 - CRITICAL - Unexpected error occurred while starting the server: [Errno 98] error while attempting to bind on address ('0.0.0.0', 44445): address already in use
2025-03-21 16:55:52,347 - INFO - Client connected: ('127.0.0.1', 43060)
2025-03-21 16:55:52,348 - INFO - Request from client ('127.0.0.1', 43060): hello world
2025-03-21 16:55:52,352 - INFO - Response Time: 0.0041 seconds
2025-03-21 16:55:52,353 - INFO - Response sent to client: ('127.0.0.1', 43060)
2025-03-21 16:55:52,353 - INFO - Connection closed for client: ('127.0.0.1', 43060)
2025-03-21 16:55:53,358 - INFO - Memory Usage: 16.0%
2025-03-21 16:55:53,359 - INFO - CPU Usage: 0.0%
2025-03-21 16:55:53,359 - INFO - Total Requests: 2, Successful Requests: 2, Failed Requests: 0
2025-03-21 17:00:43,727 - INFO - Creating SSL context...
2025-03-21 17:00:43,729 - CRITICAL - Unexpected error occurred while starting the server: [Errno 98] error while attempting to bind on address ('0.0.0.0', 44445): address already in use
2025-03-21 17:13:05,422 - INFO - Creating SSL context...
2025-03-21 17:13:05,423 - CRITICAL - Unexpected error occurred while starting the server: [Errno 98] error while attempting to bind on address ('0.0.0.0', 44445): address already in use
2025-03-21 17:13:13,439 - INFO - Client connected: ('127.0.0.1', 44972)
2025-03-21 17:13:13,440 - INFO - Request from client ('127.0.0.1', 44972): hello
2025-03-21 17:13:13,444 - INFO - Response Time: 0.0034 seconds
2025-03-21 17:13:13,444 - INFO - Response sent to client: ('127.0.0.1', 44972)
2025-03-21 17:13:13,445 - INFO - Connection closed for client: ('127.0.0.1', 44972)
2025-03-21 17:13:14,449 - INFO - Memory Usage: 16.0%
2025-03-21 17:13:14,450 - INFO - CPU Usage: 0.0%
2025-03-21 17:13:14,451 - INFO - Total Requests: 3, Successful Requests: 3, Failed Requests: 0
2025-03-21 17:13:43,958 - INFO - Client connected: ('127.0.0.1', 53898)
2025-03-21 17:13:43,959 - INFO - Request from client ('127.0.0.1', 53898): hello world
2025-03-21 17:13:43,962 - INFO - Response Time: 0.0026 seconds
2025-03-21 17:13:43,962 - INFO - Response sent to client: ('127.0.0.1', 53898)
2025-03-21 17:13:43,963 - INFO - Connection closed for client: ('127.0.0.1', 53898)
2025-03-21 17:13:44,967 - INFO - Memory Usage: 16.0%
2025-03-21 17:13:44,968 - INFO - CPU Usage: 0.0%
2025-03-21 17:13:44,969 - INFO - Total Requests: 4, Successful Requests: 4, Failed Requests: 0
2025-03-21 18:22:19,434 - INFO - Creating SSL context...
2025-03-21 18:22:19,436 - CRITICAL - Unexpected error occurred while starting the server: [Errno 98] error while attempting to bind on address ('0.0.0.0', 44445): address already in use
2025-03-21 18:22:24,313 - INFO - Client connected: ('127.0.0.1', 46478)
2025-03-21 18:22:24,319 - INFO - Request from client ('127.0.0.1', 46478): hello world
2025-03-21 18:22:24,343 - INFO - Response Time: 0.0233 seconds
2025-03-21 18:22:24,344 - INFO - Response sent to client: ('127.0.0.1', 46478)
2025-03-21 18:22:24,344 - INFO - Connection closed for client: ('127.0.0.1', 46478)
2025-03-21 18:22:25,357 - INFO - Memory Usage: 16.3%
2025-03-21 18:22:25,358 - INFO - CPU Usage: 0.0%
2025-03-21 18:22:25,359 - INFO - Total Requests: 5, Successful Requests: 5, Failed Requests: 0
2025-03-21 18:22:27,105 - INFO - Client connected: ('127.0.0.1', 46484)
2025-03-21 18:22:27,106 - INFO - Request from client ('127.0.0.1', 46484): hello
2025-03-21 18:22:27,109 - INFO - Response Time: 0.0028 seconds
2025-03-21 18:22:27,109 - INFO - Response sent to client: ('127.0.0.1', 46484)
2025-03-21 18:22:27,110 - INFO - Connection closed for client: ('127.0.0.1', 46484)
2025-03-21 18:22:28,115 - INFO - Memory Usage: 16.3%
2025-03-21 18:22:28,116 - INFO - CPU Usage: 0.5%
2025-03-21 18:22:28,116 - INFO - Total Requests: 6, Successful Requests: 6, Failed Requests: 0
2025-05-09 14:23:38,583 - ERROR - Unhandled exception: Configured file path does not exist: ${LINUX_PATH}
Traceback (most recent call last):
  File "/mnt/c/Users/ADMIN/Desktop/Standard Introductory Test Task/server.py", line 584, in <module>
    main()
  File "/mnt/c/Users/ADMIN/Desktop/Standard Introductory Test Task/server.py", line 536, in main
    config = ServerConfig(config_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/ADMIN/Desktop/Standard Introductory Test Task/server.py", line 65, in __init__
    self.validate_file_path(self.file_path)
  File "/mnt/c/Users/ADMIN/Desktop/Standard Introductory Test Task/server.py", line 98, in validate_file_path
    raise FileNotFoundError(
FileNotFoundError: Configured file path does not exist: ${LINUX_PATH}
2025-05-09 14:26:23,290 - INFO - Creating SSL context...
2025-05-09 14:26:23,293 - INFO - Server started on ('0.0.0.0', 44445)
2025-05-09 14:26:23,293 - INFO - Server is running...
2025-05-09 14:26:37,218 - INFO - Shutting down server...
2025-05-09 14:26:37,219 - INFO - Server connections closed.
2025-05-09 14:26:37,219 - INFO - Shutting down executor...
2025-05-09 14:26:37,223 - INFO - Executor shut down successfully.
2025-05-09 14:26:37,223 - INFO - Server shut down successfully.
2025-05-09 14:26:37,223 - INFO - Final Total Requests: 0
2025-05-09 14:26:37,223 - INFO - Final Successful Requests: 0
2025-05-09 14:26:37,224 - INFO - Final Failed Requests: 0
2025-05-09 14:28:15,369 - ERROR - Unhandled exception: Configured file path is a directory, not a file: /mnt/c/Users/ADMIN/Desktop/Standard Introductory Test Task
Traceback (most recent call last):
  File "/mnt/c/Users/ADMIN/Desktop/Standard Introductory Test Task/server.py", line 584, in <module>
    main()
  File "/mnt/c/Users/ADMIN/Desktop/Standard Introductory Test Task/server.py", line 536, in main
    config = ServerConfig(config_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/ADMIN/Desktop/Standard Introductory Test Task/server.py", line 65, in __init__
    self.validate_file_path(self.file_path)
  File "/mnt/c/Users/ADMIN/Desktop/Standard Introductory Test Task/server.py", line 102, in validate_file_path
    raise ValueError(
ValueError: Configured file path is a directory, not a file: /mnt/c/Users/ADMIN/Desktop/Standard Introductory Test Task
2025-05-09 14:42:11,979 - ERROR - Unhandled exception: Configured file path does not exist: ${LINUX_PATH}
Traceback (most recent call last):
  File "/mnt/c/Users/ADMIN/Desktop/Standard Introductory Test Task/server.py", line 584, in <module>
    main()
  File "/mnt/c/Users/ADMIN/Desktop/Standard Introductory Test Task/server.py", line 536, in main
    config = ServerConfig(config_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/ADMIN/Desktop/Standard Introductory Test Task/server.py", line 65, in __init__
    self.validate_file_path(self.file_path)
  File "/mnt/c/Users/ADMIN/Desktop/Standard Introductory Test Task/server.py", line 98, in validate_file_path
    raise FileNotFoundError(
FileNotFoundError: Configured file path does not exist: ${LINUX_PATH}
2025-05-09 14:42:53,999 - CRITICAL - Unexpected error occurred while starting the server: CERT_PATH environment variable must be set.
2025-05-09 14:43:27,464 - CRITICAL - Unexpected error occurred while starting the server: CERT_PATH environment variable must be set.
2025-05-09 14:43:50,365 - CRITICAL - Unexpected error occurred while starting the server: CERT_PATH environment variable must be set.
2025-05-09 14:44:22,851 - CRITICAL - Unexpected error occurred while starting the server: CERT_PATH environment variable must be set.
2025-05-09 14:46:39,354 - CRITICAL - Unexpected error occurred while starting the server: KEY_PATH environment variable must be set.
2025-05-09 14:47:52,858 - INFO - Creating SSL context...
2025-05-09 14:47:52,859 - INFO - Server started on ('0.0.0.0', 44445)
2025-05-09 14:47:52,859 - INFO - Server is running...
2025-05-09 14:48:07,736 - INFO - Client connected: ('127.0.0.1', 44548)
2025-05-09 14:48:07,738 - INFO - Request from client ('127.0.0.1', 44548): your query string
2025-05-09 14:48:07,903 - INFO - Response Time: 0.1636 seconds
2025-05-09 14:48:07,903 - INFO - Response sent to client: ('127.0.0.1', 44548)
2025-05-09 14:48:07,904 - INFO - Connection closed for client: ('127.0.0.1', 44548)
2025-05-09 14:48:08,916 - INFO - Memory Usage: 40.8%
2025-05-09 14:48:08,917 - INFO - CPU Usage: 5.5%
2025-05-09 14:48:08,918 - INFO - Total Requests: 1, Successful Requests: 1, Failed Requests: 0
2025-05-09 14:48:54,881 - INFO - Client connected: ('127.0.0.1', 46776)
2025-05-09 14:48:54,881 - INFO - Request from client ('127.0.0.1', 46776): hello world
2025-05-09 14:48:54,885 - INFO - Response Time: 0.0027 seconds
2025-05-09 14:48:54,886 - INFO - Response sent to client: ('127.0.0.1', 46776)
2025-05-09 14:48:54,887 - INFO - Connection closed for client: ('127.0.0.1', 46776)
2025-05-09 14:48:55,893 - INFO - Memory Usage: 40.9%
2025-05-09 14:48:55,894 - INFO - CPU Usage: 1.8%
2025-05-09 14:48:55,894 - INFO - Total Requests: 2, Successful Requests: 2, Failed Requests: 0
